### ISSUE TITLE
gui folder not added

### ISSUE THREAD

**Issue by T2eemo** [Pinguu-dev/PINGUU-VAL#11]
![gui](https://user-images.githubusercontent.com/101487900/158042732-21f808a0-e621-4d0b-bc4e-347fdfa79b40.png)

u didnt add the gui folder that i should include :< pls fix

**Comment by Pinguu-dev** [comment]
> ![gui](https://user-images.githubusercontent.com/101487900/158042732-21f808a0-e621-4d0b-bc4e-347fdfa79b40.png)
> 
> u didnt add the gui folder that i should include :< pls fix

You don't need it.
