### ISSUE TITLE
Crashes after 10 Minutes

### ISSUE THREAD

**Issue by xehn1337** [Pinguu-dev/PINGUU-VAL#12]
I Inject Normally and my Valorant Crashes after 10 Minutes

**Comment by iFlyn-karam-def** [comment]
How'd U add the GUI?

**Comment by iFlyn-karam-def** [comment]
And use windows 1809 for this
Turn off antivirus 
Restart PC

**Comment by xehn1337** [comment]
lmao wtf are you talking, I compile the source and can play for about 10 minutes and then it crashes, I think it's a vanguard protection because of the ESP.

**Comment by iFlyn-karam-def** [comment]
How did u compile it? , and how did u get a GUI , add me on disc Flynnn#0001

**Comment by FranklinOP-IND** [comment]
> lmao wtf are you talking, I compile the source and can play for about 10 minutes and then it crashes, I think it's a vanguard protection because of the ESP.

first time run working 1 hour after crash 10 minit i think Structs and Offsets code problem

**Comment by iFlyn-karam-def** [comment]
> 

How do u compile the fucking source code with its GUI please help xDD

**Comment by iFlyn-karam-def** [comment]
and can someone check my issue?

**Comment by FranklinOP-IND** [comment]
> and can someone check my issue?

put here vc error

**Comment by iFlyn-karam-def** [comment]
> > and can someone check my issue?
> 
> put here vc error

Im getting 97 errrors when I try running the code

**Comment by FranklinOP-IND** [comment]
> > > and can someone check my issue?
> > 
> > 
> > put here vc error
> 
> Im getting 97 errrors when I try running the code

https://stackoverflow.com/questions/4931151/cannot-open-include-file-d3dx9-h

Set All

**Comment by iFlyn-karam-def** [comment]
would be a great help if u would help me with this , sorry for troubling you

**Comment by iFlyn-karam-def** [comment]
> > lmao wtf are you talking, I compile the source and can play for about 10 minutes and then it crashes, I think it's a vanguard protection because of the ESP.
> 
> first time run working 1 hour after crash 10 minit i think Structs and Offsets code problem

Try Getting a better injector , its like vanguard is warning you , i'll try once i fixed , if same issue , we gotta wait for the updated structs and offsets

**Comment by xehn1337** [comment]
> > > lmao wtf are you talking, I compile the source and can play for about 10 minutes and then it crashes, I think it's a vanguard protection because of the ESP.
> > 
> > 
> > first time run working 1 hour after crash 10 minit i think Structs and Offsets code problem
> 
> Try Getting a better injector , its like vanguard is warning you , i'll try once i fixed , if same issue , we gotta wait for the updated structs and offsets

The Offsets and Structs are NEW and if u dont know how to include a fucking path then dont try to compile it LMAO

**Comment by iFlyn-karam-def** [comment]
> 

can u tell me how?



my error when runnin the code

Error MSB3721 The command "ml64.exe /c /nologo /Zi /Fo"x64\Debug_spoofer_stub.obj" /W3 /errorReport:prompt /Ta_spoofer_stub.asm" exited with code 1. valo C:\Program Files\Microsoft Visual

**Comment by xehn1337** [comment]
ong stfu try yourself holy shit
