### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by iFlyn-karam-def** [Pinguu-dev/PINGUU-VAL#13]
How can i setup

**Comment by Hymerine** [comment]
Compile the dll?

**Comment by iFlyn-karam-def** [comment]
> Compile the dll?

Mind telling how

**Comment by vk-nom** [comment]
if u dont know anything about cpp you shouldnt be here

**Comment by Pinguu-dev** [comment]
> if u dont know anything about cpp you shouldnt be here

And with that i close this :)
