### ISSUE TITLE
Which can i use loader

### ISSUE THREAD

**Issue by FranklinOP-IND** [Pinguu-dev/PINGUU-VAL#14]
I am Using Face Injector

**Comment by iFlyn-karam-def** [comment]
you can use guided hacking injector , 

its rlly gud 


About the previous thread , I’m getting this now 

Error MSB3721 The command "ml64.exe /c /nologo /Zi /Fo"x64\Debug_spoofer_stub.obj" /W3 /errorReportrompt /Ta_spoofer_stub.asm" exited with code 1. valo C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\masm.targets 70

**Comment by Pinguu-dev** [comment]
> you can use guided hacking injector ,
> 
> its rlly gud
> 
> About the previous thread , I’m getting this now
> 
> Error MSB3721 The command "ml64.exe /c /nologo /Zi /Fo"x64\Debug_spoofer_stub.obj" /W3 /errorReportrompt /Ta_spoofer_stub.asm" exited with code 1. valo C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\masm.targets 70

You can't

**Comment by FranklinOP-IND** [comment]
> > you can use guided hacking injector ,
> > its rlly gud
> > About the previous thread , I’m getting this now
> > Error MSB3721 The command "ml64.exe /c /nologo /Zi /Fo"x64\Debug_spoofer_stub.obj" /W3 /errorReportrompt /Ta_spoofer_stub.asm" exited with code 1. valo C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\masm.targets 70
> 
> You can't

After 10 game crash winver - 1803
