### ISSUE TITLE
copyright

### ISSUE THREAD

**Issue by FranklinOP-IND** [Pinguu-dev/PINGUU-VAL#15]
![image](https://user-images.githubusercontent.com/64591314/160647541-b9371833-7f41-4d2b-844a-293647d8a1ba.png)
someone copy your source and create own

**Comment by iFlyn-karam-def** [comment]
well its obvious , so much people did

**Comment by Pinguu-dev** [comment]
Thanks, but it's not my source either. Read through the credits. :)
And that's honestly what it's there for, let everyone do what they want with it.

If someone wants to give me a credit, he should do it, but I don't care at all. You have to expect that when something is published.

I didn't post it for attention, rather in case it was of some use to someone. But you must always mention that this complete project is the last shit. You should not really take an example from the code. ^^
