### ISSUE TITLE
Aimbot

### ISSUE THREAD

**Issue by palmiyecpp** [Pinguu-dev/PINGUU-VAL#18]
Uptaded offsets but aimbot crashing. Any fix for aimbot?
-
4.07 (for new patch use this)
0x9030840 State
0x9030878 Key

**Comment by AqramJR** [comment]
LineOfSight is outdated I think

**Comment by Pinguu-dev** [comment]
LineOfSight Offset: 0x4AC8820

**Comment by palmiyecpp** [comment]
Now works fine, thanks. -Closed
