### ISSUE TITLE
LNK2001 Error

### ISSUE THREAD

**Issue by FranklinOP-IND** [Pinguu-dev/PINGUU-VAL#19]
![image](https://user-images.githubusercontent.com/64591314/163313694-f7c7ff63-02f9-4686-9ced-861ad3816eb5.png)
Configration Error ? how it Fix that

**Comment by Pinguu-dev** [comment]
Include the DirectX SDK :)

**Comment by FranklinOP-IND** [comment]
Thnax Bro
