### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by v4ngels** [Pinguu-dev/PINGUU-VAL#2]
Hey, I saw the code on Unknowncheats, but I can't really understand how to use it, because I am very new to this. I saw somebody mention FaceInjector, is it something you need to use the cheat?

**Comment by Pinguu-dev** [comment]
If you don't know something about injection you should not use it. If you use a public injector (like face injector) without your own touch you will get a ban for 100%

**Comment by v4ngels** [comment]
> If you don't know something about injection you should not use it. If you use a public injector (like face injector) without your own touch you will get a ban for 100%
> 
> Public Stuff = Ban

Is there any guide on how to use it or hide it somehow? I see such posts every day on unknwocheats forum, but I just can't use it anytime. I have missed many opportunities this way
