### ISSUE TITLE
vs errors

### ISSUE THREAD

**Issue by mrpasta123** [Pinguu-dev/PINGUU-VAL#4]
So i tried to compile the source without changing anything in it , and i get those errors :

![errors](https://user-images.githubusercontent.com/99688855/154079988-c439fc6a-f883-4cf6-ba60-d4cc6aa9d5f5.PNG)

**Comment by pebu1337** [comment]
https://stackoverflow.com/questions/4931151/cannot-open-include-file-d3dx9-h

**Comment by mrpasta123** [comment]
not workin

**Comment by iFlyn-karam-def** [comment]
I have these errors now 
Error MSB3721 The command "ml64.exe /c /nologo /Zi /Fo"x64\Debug_spoofer_stub.obj" /W3 /errorReportrompt /Ta_spoofer_stub.asm" exited with code 1. valo C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\masm.targets 70
